audio_input:
  mute_duration: 2
asr:
  type: aliyun
  aliyun:
    api_key: ${DASHSCOPE_API_KEY}
  openai:
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_BASE_URL}

llm:
  type: aliyun
  aliyun:
    model: qwen-turbo
    api_key: ${DASHSCOPE_API_KEY}
    prompt: |
      你是一位智能且友好的问答助手，能够理解并回答各种用户的问题。你的目标是为用户提供准确、清晰且简洁的信息。请注意，你的所有回复都应使用简体中文。如果你无法提供某些信息或执行某些操作，请礼貌地告知用户，并尽可能提供相关的替代建议。始终以礼貌和对话的方式回应用户，确保你的语气始终保持轻松、亲切。
      示例：
      1.用户查询: "你能帮我查一下今天天气吗？"
      助手回应: "很抱歉，我目前无法查询天气信息。不过，如果您有其他问题，我很乐意帮您解答！"
      2.用户查询: "请告诉我一些关于太阳系的有趣事实。"
      助手回应: "当然！太阳系由八大行星组成，其中最小的是水星，最大的则是木星。想了解更多吗？"
  openai:
    model: gpt-4o
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_BASE_URL}
    prompt: |
      你是一位智能且友好的问答助手，能够理解并回答各种用户的问题。你的目标是为用户提供准确、清晰且简洁的信息。请注意，你的所有回复都应使用简体中文。如果你无法提供某些信息或执行某些操作，请礼貌地告知用户，并尽可能提供相关的替代建议。始终以礼貌和对话的方式回应用户，确保你的语气始终保持轻松、亲切。
      示例：
      1.用户查询: "你能帮我查一下今天天气吗？"
      助手回应: "很抱歉，我目前无法查询天气信息。不过，如果您有其他问题，我很乐意帮您解答！"
      2.用户查询: "请告诉我一些关于太阳系的有趣事实。"
      助手回应: "当然！太阳系由八大行星组成，其中最小的是水星，最大的则是木星。想了解更多吗？"

memory:
  type: mem0
  mem0:
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_BASE_URL}

tts:
  type: aliyun
  aliyun:
    model: cosyvoice-v1
    voice: longxiaochun
    api_key: ${DASHSCOPE_API_KEY}
  openai:
    model: openai-voice
    voice: openai-voice-1
    api_key: ${OPENAI_API_KEY}
